### ISSUE TITLE
Docker-compose link not working

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4038]
**VIC version:**

build 8158

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
```bin/vic-machine-linux create --name=vch-1 --volume-store=datastore1/test:default  --target=root:pwd@192.168.60.162 --thumbprint=...  --debug 1 --no-tlsverify --no-tls```

**Steps to reproduce:**
Here is the docker-compose.yml
```
version: '3'
services:
  db:
    image: busybox
    links:
      - web:aaa
    command: ["ping", "aaa"]
    depends_on:
      - web

  web:
    image: busybox
    container_name: a.b
    command: ["/bin/top"]
```

**Actual behavior:**
The alias does not work. Here is the output from docker-compose logs
```
Attaching to vic_db_1, a.b
db_1   | ping: bad address 'aaa'
```

**Expected behavior:**
"ping aaa" from db should work.

**Additional details as necessary:**
However, if we specify using the default bridge network as the the default network to use in the compose file, it works fine.
```
version: '3'
services:
  db:
    image: busybox
    links:
      - web:aaa
    command: ["ping", "aaa"]
    depends_on:
      - web

  web:
    image: busybox
    container_name: a.b
    command: ["/bin/top"]

networks:
  default:
    external:
      name: bridge
```
