### ISSUE TITLE
working yml file for quick docker-compose demo

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#4926]
I am posting this for anyone who wants to do a quick demo of docker-compose with VIC. Apologies, if my search skill wasn't good; I couldn't get a quick working sample from any docs.

```
version: '2'

services:

  mydb:
    image: ipaddress/project/mariadb
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=somewordpress
       - MYSQL_DATABASE=wordpress
       - MYSQL_USER=wordpress
       - MYSQL_PASSWORD=wordpress
    networks:
       - backend

  myapp:
    depends_on:
       - mydb
    image: ipaddress/project/wordpress
    networks:
       - backend
    ports:
      - 9080:80
    restart: always
    environment:
       - WORDPRESS_DB_HOST=mydb
       - WORDPRESS_DB_USER=wordpress
       - WORDPRESS_DB_PASSWORD=wordpress
networks:
  backend:
    driver: bridge

```

hope this helps.
