### ISSUE TITLE
Need a better error message for trying to share non-NFS volumes.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#6531]
see https://github.com/vmware/vic/issues/2303#issuecomment-335165185

If a user tries to share a non-NFS volume, there should be a better error message than described.

**Comment by mshipkovenski** [comment]
Steps to reproduce (using Admiral):
1. Configure a VCH host (v1.2.1, default datastore1) and add it to Admiral
2. Import the following compose file in Admiral (Library > Template > Import Template):

```
---
version: "2"
services:
  hello-world-nginx:
    image: "registry.hub.docker.com/kitematic/hello-world-nginx"
    volumes:
    - "test-vol:/tmp"
    restart: "no"
  hello-world-nginx-2:
    image: "registry.hub.docker.com/kitematic/hello-world-nginx"
    volumes:
    - "test-vol:/tmp"
    restart: "no"
volumes:
  test-vol:
    external: false
```

3. Try to deploy an app based on the template. Provisioning fails with:
`Service https://10.160.147.28:2376/v1.24/containers/05b9b9874d0f0965476d377398d33e42e866258a2fb0de54c0bc95ddd8864735/start returned error 500 for POST. id 109716 message Server error from portlayer: unable to wait for process launch status: container VM has unexpectedly powered off; Reason: {"message":"Server error from portlayer: unable to wait for process launch status: container VM has unexpectedly powered off"}` 

The actual error that comes from VCH is after `Reason:`.
